Website/config/routes.rb
Website::Application.routes.draw do
  devise_for :users
  resources :images
  resources :teches
  resources :projects
  resources :bios
  root :to => "home#index"
  get 'about', to: "home#about"
  get 'works', to: "home#works"
  get 'contact', to: "home#contact"

end

Website/app/models/bio.rb
class Bio < ActiveRecord::Base
end

Website/app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :project
end

Website/app/models/project.rb
class Project < ActiveRecord::Base
  has_many :images
  has_and_belongs_to_many :teches
  accepts_nested_attributes_for :images, :reject_if => :all_blank
  accepts_nested_attributes_for :teches
end

Website/app/models/tech.rb
class Tech < ActiveRecord::Base
  has_and_belongs_to_many :projects
end

Website/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable,
  #
  devise :database_authenticatable, :validatable, :recoverable, :rememberable, :trackable
end

Website/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Website/app/controllers/bios_controller.rb
class BiosController < ApplicationController
  before_action :set_bio, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /bios
  # GET /bios.json
  def index
    @bios = Bio.all
  end

  # GET /bios/1
  # GET /bios/1.json
  def show
  end

  # GET /bios/new
  def new
    @bio = Bio.new
  end

  # GET /bios/1/edit
  def edit
  end

  # POST /bios
  # POST /bios.json
  def create
    @bio = Bio.new(bio_params)

    respond_to do |format|
      if @bio.save
        format.html { redirect_to @bio, notice: 'Bio was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bio }
      else
        format.html { render action: 'new' }
        format.json { render json: @bio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bios/1
  # PATCH/PUT /bios/1.json
  def update
    respond_to do |format|
      if @bio.update(bio_params)
        format.html { redirect_to @bio, notice: 'Bio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bios/1
  # DELETE /bios/1.json
  def destroy
    @bio.destroy
    respond_to do |format|
      format.html { redirect_to bios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bio
      @bio = Bio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bio_params
      params.require(:bio).permit(:about)
    end
end

Website/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @project1 = Project.first
    @project2 = Project.last
    @about = Bio.first

  end

  def works
    @projects = Project.all
    @pts = Tech.all
  end

end

Website/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    3.times {@project.images.build}
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :start_date, :finish_date, :description)
    end
end

Website/app/controllers/teches_controller.rb
class TechesController < ApplicationController
  before_action :set_tech, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /teches
  # GET /teches.json
  def index
    @teches = Tech.all
  end

  # GET /teches/1
  # GET /teches/1.json
  def show
  end

  # GET /teches/new
  def new
    @tech = Tech.new
  end

  # GET /teches/1/edit
  def edit
  end

  # POST /teches
  # POST /teches.json
  def create
    @tech = Tech.new(tech_params)

    respond_to do |format|
      if @tech.save
        format.html { redirect_to @tech, notice: 'Tech was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tech }
      else
        format.html { render action: 'new' }
        format.json { render json: @tech.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teches/1
  # PATCH/PUT /teches/1.json
  def update
    respond_to do |format|
      if @tech.update(tech_params)
        format.html { redirect_to @tech, notice: 'Tech was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tech.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teches/1
  # DELETE /teches/1.json
  def destroy
    @tech.destroy
    respond_to do |format|
      format.html { redirect_to teches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tech
      @tech = Tech.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tech_params
      params.require(:tech).permit(:name)
    end
end

Website/app/helpers/application_helper.rb
module ApplicationHelper
end

Website/app/helpers/bios_helper.rb
module BiosHelper
end

Website/app/helpers/home_helper.rb
module HomeHelper
end

Website/app/helpers/images_helper.rb
module ImagesHelper
end

Website/app/helpers/projects_helper.rb
module ProjectsHelper

end

Website/app/helpers/teches_helper.rb
module TechesHelper
end

Website/app/views/bios/_form.html.erb
<%= form_for(@bio) do |f| %>
  <% if @bio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bio.errors.count, "error") %> prohibited this bio from being saved:</h2>

      <ul>
      <% @bio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_area :about %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Website/app/views/bios/edit.html.erb
<h1>Editing bio</h1>

<%= render 'form' %>

<%= link_to 'Show', @bio %> |
<%= link_to 'Back', bios_path %>

Website/app/views/bios/index.html.erb
<h1>Listing bios</h1>

<table>
  <thead>
    <tr>
      <th>About</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bios.each do |bio| %>
      <tr>
        <td><%= bio.about %></td>
        <td><%= link_to 'Show', bio %></td>
        <td><%= link_to 'Edit', edit_bio_path(bio) %></td>
        <td><%= link_to 'Destroy', bio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bio', new_bio_path %>

Website/app/views/bios/new.html.erb
<h1>New bio</h1>

<%= render 'form' %>

<%= link_to 'Back', bios_path %>

Website/app/views/bios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>About:</strong>
  <%= @bio.about %>
</p>

<%= link_to 'Edit', edit_bio_path(@bio) %> |
<%= link_to 'Back', bios_path %>

Website/app/views/home/contact.html.erb
<div class="row">

  <div class="col-md-6 col-sm-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <h2>KM</h2>
      </div>
    </div>
  </div>

  <div class="col-md-6 col-sm-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <h2>Kylie Mabey</h2>
        <h3>Front-end Developer / UX Designer</h3>
        <h3>Email: kyliemabey@gmail.com</h3>
        <h3>Salt Lake City, Utah</h3>
        <div class="row">
          <div class="col-md-6 col-sm-12">
            <p>Social icon for linked in goes here.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

Website/app/views/home/index.html.erb
<div class="row">
    <div class="col-lg-5 col-md-12 quoteHolder">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="col-md-7">
          <blockquote class="pull-right">
            <p>“Intuitive design is how we give the user new superpowers.”</p>
            <small>Jared Spool, <cite title="Web Site Usability">Web Site Usability: A Designer's Guide</cite></small>
          </blockquote>
          </div>
          <div class="col-md-5">
              <div class="imgLeft"></div>
          </div>
        </div>
      </div>
    </div>
  <div class="col-lg-7 col-md-12 aboutHolder">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">About</h3>
      </div>
      <div class="panel-body">
        <h5> <%= @about.about %> </h5>
      </div>
    </div>
  </div>
</div>

<div class="row">
    <div class="col-lg-5 col-md-12 skillsHolder">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Primary Skills</h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <img src="/assets/html5_css3_js.png" alt="HTML5 CSS3 JS" class="skillImgsHCJ"/>
            <img src="/assets/c-sharp.png" alt="C-Sharp" class="skillImgs"/>
            <img src="/assets/adobe.png" alt="Adobe" class="skillImgs"/>
          </div>
        </div>
      </div>
    </div>
  <div class="col-lg-7 col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Works</h3>
      </div>
      <div class="panel-body">
          <div class="col-lg-6 col-md-12 clearfix">
            <div class="thumbnail">
              <img src="/assets/test.jpg" alt="project01">
              <div class="caption">
                <h3><%= @project1.name %></h3>
                <p><%= @project1.description %></p>
                <p><a href="#" class="btn btn-primary pull-right" role="button">Details</a></p>
              </div>
            </div>
          </div>
        <div class="col-lg-6 col-md-12 clearfix">
          <div class="thumbnail">
            <img src="/assets/test.jpg" alt="project02">
            <div class="caption">
              <h3><%= @project2.name %></h3>
              <p><%= @project2.description %></p>
              <p><a href="#" class="btn btn-primary pull-right" role="button">Details</a></p>
            </div>
          </div>
        </div>
        <a href="#" class="btn btn-primary pull-right" role="button">View All Works</a>
      </div>
    </div>
  </div>
</div>

Website/app/views/home/works.html.erb
<div class="row">
  <div class="col-md-12 myTabs">
    <ul class="nav nav-tabs nav-tabs-justified">
      <% @projects.each do |project| %>
        <li>
          <a data-toggle="tab" href="#<%=project.id%>"><%= project.name%></a>
        </li>
      <% end %>
    </ul>
    <div class="tab-content">
      <%= @projects.each do |p| %>
          <div class="tab-pane fade in panel panel-default" id="<%= p.id %>">
            <div class="row">
              <div class="panel-body">
                <div class="col-md-7 col-sm-12">
                  <h3><%= p.name %></h3>
                  <div class="row">
                    <h5><%= p.description %></h5>
                    <h5>Start Date: <%= p.start_date %></h5>
                    <h5>End Date: <%= p.finish_date %></h5>
                    <h5>Technologies Used:</h5>
                      <%= p.teches.name %>
                  </div>
                </div>
                <div class="col-md-5 col-sm-12">
                  Images go here.
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

Website/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kylie Mabey</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="background">
    <div class="row">
      <div class="col-md-2">
      </div>
      <div class="col-md-8 well mainContainer">
        <div class="row">
          <div class="col-md-2">

          </div>
          <div class="col-md-8 logo">
            <a href="/"><h1>Kylie Mabey</h1></a>
          </div>
          <div class="col-md-2 pull-right">
            <div class="imgRight"></div>
          </div>
        </div>
        <div class="row headAndNav">
          <div class="col-md-12">
            <ul class="nav nav-pills nav-justified">
              <li><a href="/works">Works</a></li>
              <li><a href="/contact">Contact</a></li>
            </ul>
          </div>
        </div>
          <%= yield %>
        <div class="row">
          <div class="col-md-12">
            <footer class="pull-right">
              <% if user_signed_in? %>
                  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              <% else %>
                  <%= link_to('Login', new_user_session_path)  %>
              <% end %>
              &copy Kylie Ann Mabey - 2013
            </footer>
          </div>
        </div>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
<script>
    $.ajaxSetup({cache: false});
    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
        var target = $(e.target).attr("href") // activated tab
        if ($(target).is(':empty')) {
            $.ajax({
                type: "GET"//,
                //url: "/article/"
            })
        }
    })
</script>
</body>
</html>

Website/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :finish_date %><br>
    <%= f.date_select :finish_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

    <p>Images</p>
    <%= f.fields_for :images do |ff| %>
        <div>
          <%= ff.label :name %>
          <%= ff.text_field :name %>
        </div>
    <% end %>

    <p>Tech Used</p>
    <%= collection_check_boxes(:project, :tech_ids, Tech.all, :id, :name) %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Website/app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

Website/app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>Finish date</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.start_date %></td>
        <td><%= project.finish_date %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

Website/app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

Website/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</p>

<p>
  <strong>Finish date:</strong>
  <%= @project.finish_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

Website/app/views/teches/_form.html.erb
<%= form_for(@tech) do |f| %>
  <% if @tech.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tech.errors.count, "error") %> prohibited this tech from being saved:</h2>

      <ul>
      <% @tech.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Website/app/views/teches/edit.html.erb
<h1>Editing tech</h1>

<%= render 'form' %>

<%= link_to 'Show', @tech %> |
<%= link_to 'Back', teches_path %>

Website/app/views/teches/index.html.erb
<h1>Listing teches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @teches.each do |tech| %>
      <tr>
        <td><%= tech.name %></td>
        <td><%= link_to 'Show', tech %></td>
        <td><%= link_to 'Edit', edit_tech_path(tech) %></td>
        <td><%= link_to 'Destroy', tech, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tech', new_tech_path %>

Website/app/views/teches/new.html.erb
<h1>New tech</h1>

<%= render 'form' %>

<%= link_to 'Back', teches_path %>

Website/app/views/teches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tech.name %>
</p>

<%= link_to 'Edit', edit_tech_path(@tech) %> |
<%= link_to 'Back', teches_path %>